name: Common CI - Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    
    - name: Download and install deb packages
      run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install g++ -y

    - name: Node.js Setup
      uses: actions/setup-node@v2
      with:
        node-version: lts/dubnium
    - name: Installation of Node.js dependencies
      run: npm i